// auto-generated by evolverilog
`include "simpleAnd.v" // include the module to call

module organismSimulator;

    reg Input0,Input1; // number of Inputs Args
    wire Output0; // number of Outputs Args
    
    parameter settleDelay = 10000;
    
    simpleAnd uut (Output0,Input0,Input1); // module to call, number of Output, Input Args
    
    integer i;
    
    initial
    begin
        $display ("out,in,in"); // io structure
        // should run number of inputs ^ 2 times
        for (i = 0; i < 4; i = i + 1) begin
            {Input0,Input1} = i; // number of Input Args
            #settleDelay
            $display ("%d,%d,%d",Output0,Input0,Input1); // total args, outputs, inputs 
        end
    end
    
endmodule